### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by bdkuhman** [modmuss50/FTB-Achievements#1]
After starting server, JVM quickly runs out of memory and hangs the thread. I investigated a bit, and it appears that CraftingTiers.json is 15 mb, when the singleplayer CraftingTiers is 3kb.
It appears the json file is filled with a large number of duplicate entries. counting 
`{
      "recipeGroup": "luck3",
      "teamID": "Green Team",
      "currentTier": 0
    },` 
returns 5,872 matches.
Playing on FTB Pyramid Reborn 2.0.1

**Comment by bdkuhman** [comment]
[stacktrace.txt](https://github.com/modmuss50/FTB-Achievements/files/1834789/stacktrace.txt)

**Comment by bdkuhman** [comment]
[craftingTiers.zip](https://github.com/modmuss50/FTB-Achievements/files/1834792/craftingTiers.zip)

**Comment by modmuss50** [comment]
If you delete that file it will work for a bit. I was already aware of the issue a fix is going to be in the next pack update.

**Comment by bdkuhman** [comment]
alright. Thanks
